site_name: Luiger Pages
nav:
    - Inicio: index.md
    - Mi Blog:
        - Año Nuevo: blog/2020/0101/nuevo.md
        - Como sacar el pasaporte en el Tachira: blog/2022/2603/pasaporte.md
        # - La magia de la vida: blog/2023/0811/lamagiadelcambio.md
        -  La AI como parte de nuestro aprendizaje: blog/2024/0809/ai.md
        - 2026 El año en que debemos estudiar más: blog/2025/1225/estudiar2025.md
    - Mis articulos:
        - Microservicios: articulos/2019/MicroSOA/micro2soa.md
    - Acerca de mi: about.md
    
theme: 
    name: bootstrap4
    